### ISSUE TITLE
cryptography.fernet.InvalidToken

### ISSUE THREAD

**Issue by bwlok** [i10b/simplematrixbotlib#145]
If I try to login with my Account the Console gives me: 

Traceback (most recent call last):
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/fernet.py", line 127, in _verify_signature
    h.verify(data[-32:])
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/primitives/hmac.py", line 72, in verify
    ctx.verify(signature)
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/hazmat/backends/openssl/hmac.py", line 85, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bwlok/Music/Matrix.py", line 18, in <module>
    bot.run()
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/simplematrixbotlib/bot.py", line 84, in run
    asyncio.run(self.main())
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode-beta.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/simplematrixbotlib/bot.py", line 43, in main
    self.creds.session_read_file()
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/simplematrixbotlib/auth.py", line 89, in session_read_file
    decrypted_session_data = fw.decrypt(
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/fernet_wrapper/__init__.py", line 37, in decrypt
    data = str(f.decrypt(token))
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/fernet.py", line 88, in decrypt
    return self._decrypt_data(data, timestamp, time_info)
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/fernet.py", line 145, in _decrypt_data
    self._verify_signature(data)
  File "/Users/bwlok/Library/Python/3.9/lib/python/site-packages/cryptography/fernet.py", line 129, in _verify_signature
    raise InvalidToken
cryptography.fernet.InvalidToken

Does anyone know how I can fix this?

**Comment by csuriano23** [comment]
I am experiencing a similar issue. Same token in js client library doesn't raise an error. Do you know how can I fix it?

**Comment by imbev** [comment]
Deleting `session.txt` should provide a temporary fix.
