### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by 42Willow** [i10b/simplematrixbotlib#169]
Raspberry Pi OS

Error:
```py
>>> import simplematrixbotlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/simplematrixbotlib/__init__.py", line 1, in <module>
    from simplematrixbotlib.api import Api
  File "/usr/local/lib/python3.9/dist-packages/simplematrixbotlib/api.py", line 3, in <module>
    from nio import (AsyncClient, SyncResponse, RoomMessageText, AsyncClientConfig)
  File "/usr/local/lib/python3.9/dist-packages/nio/__init__.py", line 2, in <module>
    from .client import *
  File "/usr/local/lib/python3.9/dist-packages/nio/client/__init__.py", line 3, in <module>
    from .base_client import Client, ClientConfig
  File "/usr/local/lib/python3.9/dist-packages/nio/client/base_client.py", line 36, in <module>
    from ..crypto import ENCRYPTION_ENABLED
  File "/usr/local/lib/python3.9/dist-packages/nio/crypto/__init__.py", line 23, in <module>
    from .sessions import (
  File "/usr/local/lib/python3.9/dist-packages/nio/crypto/sessions.py", line 23, in <module>
    import olm
  File "/usr/local/lib/python3.9/dist-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/__init__.py", line 24, in <module>
    from .utility import ed25519_verify, OlmVerifyError, OlmHashError, sha256
  File "/usr/local/lib/python3.9/dist-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/olm/utility.py", line 39, in <module>
    from _libolm import ffi, lib  # type: ignore
ImportError: /usr/local/lib/python3.9/dist-packages/python_olm-3.2.13-py3.9-linux-armv7l.egg/_libolm.abi3.so: undefined symbol: _ZNSt8ios_base4InitD1Ev
```

main.py
```py
# echo.py
# Example:
# randomuser - "!echo example string"
# echo_bot - "example string"

import simplematrixbotlib as botlib

creds = botlib.Creds("https://matrix.org", "exampleuser", "examplepassword")
bot = botlib.Bot(creds)
PREFIX = '!'

@bot.listener.on_message_event
async def echo(room, message):
    match = botlib.MessageMatch(room, message, bot, PREFIX)

    if match.is_not_from_this_bot() and match.prefix() and match.command("echo"):

        await bot.api.send_text_message(
            room.room_id, " ".join(arg for arg in match.args())
            )

bot.run()
```

What am I doing wrong?

**Comment by 42Willow** [comment]
I used a venv on a fresh install and it seems to be working now..
