### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'

### ISSUE THREAD

**Issue by Mr-Mistoffelees** [i10b/simplematrixbotlib#174]
Hi all,

**Describe the bug**
I'm experiencing the following issue while trying out the [A Basic Echo Bot](https://simple-matrix-bot-lib.readthedocs.io/en/latest/examples.html#a-basic-echo-bot). This occours when I send a direct message to my matrix bot from another user account:

```
Connected to https://matrix.org as @USERNAME:matrix.org (IDENTIFIER)
Traceback (most recent call last):
  File "C:\path_to_project\example.py", line 21, in <module>
    bot.run()
  File "C:\path_to_project\Lib\site-packages\simplematrixbotlib\bot.py", line 88, in run
    asyncio.run(self.main())
  File "C:\Users\WINUSERNAME\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\WINUSERNAME\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WINUSERNAME\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\path_to_project\Lib\site-packages\simplematrixbotlib\bot.py", line 81, in main
    await self.async_client.sync_forever(timeout=3000, full_state=True)
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 1199, in sync_forever
    await self.run_response_callbacks([await response])
                                       ^^^^^^^^^^^^^^
  File "C:\Users\WINUSERNAME\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 1046, in sync
    response = await self._send(
               ^^^^^^^^^^^^^^^^^
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 792, in _send
    await self.receive_response(resp)
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 704, in receive_response
    await self._handle_sync(response)
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 671, in _handle_sync
    await self._handle_joined_rooms(response)
  File "C:\path_to_project\Lib\site-packages\nio\client\async_client.py", line 598, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
          ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000015E7037FD10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000015E7027BEE0>, 1624750.906)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000015E7037D750>

Process finished with exit code 1
```

**To Reproduce**

```
python -m pip install simplematrixbotlib
```

Then run
```
import simplematrixbotlib as botlib

creds = botlib.Creds("https://home.server", "user", "pass")
bot = botlib.Bot(creds)
PREFIX = '!'


@bot.listener.on_message_event
async def echo(room, message):
    match = botlib.MessageMatch(room, message, bot, PREFIX)

    if match.is_not_from_this_bot() and match.prefix() and match.command(
            "echo"):

        await bot.api.send_text_message(room.room_id,
                                        " ".join(arg for arg in match.args()))


bot.run()
```

**Expected behavior**
Do nothing or echo the message

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE: PyCharm
 - Python Version: 3.10
 - Package Version: 2.8.0

**Additional context**
Might be a stupid beginner mistake.

**Comment by Spacefreak18** [comment]
python 3.10 changed the asyncio api upon which matrixnio and consequently simplematrixbotlib is based.

So all bots are going to break, and no one is talking about it. I suspect that it will even require a coding change by each individual bot project, even after matrix-nio gets fixed and subsequently simplematrixbotlib.

Stay on debian stable with python 3.9.
